kind: Deployment
apiVersion: apps/v1
metadata:
   name: vishalbhagde
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: vishal
   template:
      metadata:
        labels:
          app: vishal
      spec:
       containers:
        - name: vishal
          image: vishal7517/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80